[tool.poetry]
name = "csu-card-read"
version = "0.1.0"
description = "查询csu宿舍电费余额并推送"
authors = ["barometer"]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
drissionpage = "^4.1.0.11"
ddddocr = "1.5.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
