name: "Github Action Push Daily"
on:
  workflow_dispatch:
  schedule:
    - cron: "30 00 * * *"

permissions:
  contents: write

jobs:
  build:
    name: "test setup browser"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install chromium
        run: sudo apt-get update && sudo apt-get install -y chromium-browser
      - name: Install Dependencies for Headless Browser
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk
          sudo apt-get install -y libgbm-dev libxshmfence-dev \
                                  libasound2 libatk1.0-0 libatk-bridge2.0-0 \
                                  libcups2 libdrm2 libxrandr2 \
                                  libgbm1 libnss3 libxss1 libxcomposite1 \
                                  libxcursor1 libxdamage1 libxfixes3 \
                                  libxinerama1 libxrender1 libxi6 libgl1 \
                                  libpango1.0-0 libgtk-3-0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run python
        env:
          COUNT: ${{ secrets.COUNT }}
          PWD: ${{ secrets.PWD }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
          GITHUB_TRIGGERING_ACTOR: ${{ github.triggering_actor }}
        run: python main.py
      - name: git config
        run: |-
          git config --global user.name "Github Actions"
          git config --global user.email "actions@gmail.com"
      - name: Push
        run: |-
          git diff
          git add -A
          git status
          git commit -m "update by github actions" || echo "No changes to commit"
          git push
